### PR TITLE
Allow show images in chat

### PR DESCRIPTION
**Pull request by ezra-obiwale**

### CODE REVIEW

**Comment by jmaczan** [comment]
Hi Ezra :slightly_smiling_face: I like the idea of nesting images in posts! I accept this PR, but in general, the feature of adding images to messages is not done. In addition to this, we need to create images uploader and add some constraints of images size

**Comment by ezra-obiwale** [comment]
@jmaczan Agreed. I only added this feature level because it's what I needed urgently.

And speaking of which, could you please publish to npm so I can at least use this feature in my project right away?

Thanks.

**Comment by jmaczan** [comment]
Sure, publish is done. @ezra-obiwale :slightly_smiling_face:

**Comment by ezra-obiwale** [comment]
@jmaczan Thanks

**Pull request merged**
